name: 'Check all lines have an equal amount of columns'

on:
  pull_request:

jobs:
  check:
    name: 'Check column count'
    runs-on: ubuntu-2204-4

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: '${{ secrets.GITHUB_TOKEN }}'

    - name: Check
      run: |
        ./scripts/test-columns.sh ems_translations.csv
        ./scripts/test-columns.sh showroom_translations.csv

