name: 'Check all translations have the right encoding'

on:
  pull_request:

jobs:
  check:
    name: 'Check encoding'
    runs-on: ubuntu-20.04

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout uses: actions/checkout@v2
      with:
        token: '${{ secrets.GITHUB_TOKEN }}'

    - name: Check
      run: |
        ./scripts/test-encoding.sh ems_translations.csv
        ./scripts/test-encoding.sh showroom_translations.csv

